'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import { User } from '@supabase/supabase-js';
import FlagIcon, { LANGUAGES } from "@/components/FlagIcon";
import { locales, localeNames, localeToTranslationCode, type Locale } from '@/i18n/config';
import Footer from '@/components/Footer';

// Translations
const translations: Record<string, Record<string, string>> = {
  EN: {
    home: "Home",
    predictions: "Predictions",
    leagues: "Leagues",
    performance: "AI Performance",
    community: "Community",
    news: "News",
    solution: "Solution",
    pricing: "Pricing",
    login: "Log In",
    getStarted: "Get Started",
    heroTitle: "Enterprise Solutions",
    heroSubtitle: "Power your platform with OddsFlow's AI-driven football prediction technology",
    signalApi: "Signal API",
    signalApiDesc: "Integrate our AI predictions directly into your platform with our robust RESTful API. Real-time odds analysis, match predictions, and probability calculations delivered at scale.",
    signalApiFeature1: "Real-time prediction endpoints",
    signalApiFeature2: "99.9% uptime SLA",
    signalApiFeature3: "Comprehensive documentation",
    signalApiFeature4: "Webhook support for live updates",
    whiteLabel: "White Label Solution",
    whiteLabelDesc: "Launch your own branded AI prediction platform. Fully customizable design, your domain, your brand identity - powered by OddsFlow technology.",
    whiteLabelFeature1: "Custom branding & design",
    whiteLabelFeature2: "Your own domain",
    whiteLabelFeature3: "Full admin dashboard",
    whiteLabelFeature4: "User management system",
    nativeAds: "Native Advertising",
    nativeAdsDesc: "Monetize your traffic with seamlessly integrated native ads. Non-intrusive placements designed to enhance user experience while maximizing revenue.",
    nativeAdsFeature1: "High CPM rates",
    nativeAdsFeature2: "Non-intrusive placements",
    nativeAdsFeature3: "Performance analytics",
    nativeAdsFeature4: "Multiple ad formats",
    dataAdvantage: "Data Advantage",
    dataAdvantageDesc: "Our AI models are built on comprehensive multi-dimensional data analysis with extensive historical backtesting to ensure prediction accuracy.",
    multiDimensional: "Multi-Dimensional Models",
    multiDimensionalDesc: "Our AI analyzes 200+ variables per match including team form, player statistics, head-to-head records, weather conditions, and market movements.",
    backtesting: "Historical Backtesting",
    backtestingDesc: "Every model is rigorously tested against 10+ years of historical data across 50+ leagues to validate prediction accuracy before deployment.",
    flexiblePricing: "Flexible Pricing",
    flexiblePricingDesc: "Choose a pricing model that fits your business. From pay-per-request to unlimited enterprise plans, we scale with your needs.",
    pricingFeature1: "Pay-per-request model",
    pricingFeature2: "Monthly subscriptions",
    pricingFeature3: "Custom enterprise deals",
    pricingFeature4: "Volume discounts available",
    contactUs: "Contact Us",
    contactUsDesc: "Ready to integrate OddsFlow into your platform? Our team is here to help you find the perfect solution for your business needs.",
    getInTouch: "Get in Touch",
    email: "Email",
    footer: "18+ | Gambling involves risk. Please gamble responsibly.",
    allRights: "© 2026 OddsFlow. All rights reserved.",
    // Why Choose Us
    whyChooseUs: "WHY CHOOSE US",
    whyChooseTitle: "Why Choose OddsFlow",
    whyChooseSubtitle: "Experience the difference with our AI-powered platform",
    benefit1Title: "99.9% Uptime",
    benefit1Desc: "Our platform runs 24/7 with enterprise-grade reliability",
    benefit2Title: "Real-time Data",
    benefit2Desc: "Get instant updates from 50+ bookmakers worldwide",
    benefit3Title: "AI Accuracy",
    benefit3Desc: "Our models achieve 78%+ prediction accuracy",
    benefit4Title: "Secure & Private",
    benefit4Desc: "Bank-level encryption protects your data",
    benefit5Title: "24/7 Support",
    benefit5Desc: "Expert support team available around the clock",
    benefit6Title: "Money Back",
    benefit6Desc: "30-day money back guarantee, no questions asked",
    // FAQ
    faqTitle: "Frequently Asked Questions",
    faq1Q: "What are AI football predictions?",
    faq1A: "AI football predictions are statistical forecasts generated by artificial intelligence. At OddsFlow, our models use historical data, team performance, and advanced algorithms to calculate the most likely outcomes for each football match.",
    faq2Q: "How accurate are your predictions?",
    faq2A: "While no prediction is guaranteed, our AI models are designed to provide high-confidence probabilities. We focus on long-term accuracy and continuous optimization to improve over time. Always remember: betting involves risk.",
    faq3Q: "How often are the predictions updated?",
    faq3A: "Predictions are updated daily, with new data and match information. In the case of late-breaking news, like injuries or lineup changes, the model automatically adjusts the probabilities.",
    faq4Q: "Do you provide betting tips or just stats?",
    faq4A: "We focus on objective AI-generated probabilities, not personal opinions. However, we may occasionally highlight high-confidence picks based on the AI model for users looking for quick insights.",
    faq5Q: "Are these predictions free to use?",
    faq5A: "Yes. Our daily AI betting predictions are completely free, with no sign-up required. We believe everyone should have access to intelligent, data-driven betting tools.",
    faq6Q: "Can I access your predictions on mobile devices?",
    faq6A: "Yes, OddsFlow is fully mobile-responsive, offering seamless access across desktop, tablet, and smartphone devices.",
    // Footer
    footerDesc: "AI-powered football odds analysis for smarter predictions. Make data-driven decisions with real-time insights.",
    product: "Product",
    liveOdds: "AI Performance",
    popularLeagues: "Popular Leagues",
    communityFooter: "Community",
    globalChat: "Global Chat",
    userPredictions: "User Predictions",
    todayMatches: "Today Matches",
    company: "Company",
    aboutUs: "About Us",
    contact: "Contact",
    blog: "Blog",
    legal: "Legal",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    responsibleGaming: "Responsible Gaming",
    allRightsReserved: "All rights reserved.",
    gamblingWarning: "Gambling involves risk. Please gamble responsibly.",
    disclaimer: "Disclaimer: OddsFlow provides AI-powered predictions for informational and entertainment purposes only. We do not guarantee the accuracy of predictions and are not responsible for any financial losses. Gambling involves risk. Please gamble responsibly. If you or someone you know has a gambling problem, please seek help. Users must be 18+ years old.",
  },
  ES: {
    home: "Inicio",
    predictions: "Predicciones",
    leagues: "Ligas",
    performance: "Rendimiento IA",
    community: "Comunidad",
    news: "Noticias",
    solution: "Solución",
    pricing: "Precios",
    login: "Iniciar Sesión",
    getStarted: "Comenzar",
    heroTitle: "Soluciones Empresariales",
    heroSubtitle: "Potencia tu plataforma con la tecnología de predicción de fútbol impulsada por IA de OddsFlow",
    signalApi: "API de Señales",
    signalApiDesc: "Integra nuestras predicciones de IA directamente en tu plataforma con nuestra robusta API RESTful. Análisis de cuotas en tiempo real, predicciones de partidos y cálculos de probabilidad a escala.",
    signalApiFeature1: "Endpoints de predicción en tiempo real",
    signalApiFeature2: "SLA de 99.9% de disponibilidad",
    signalApiFeature3: "Documentación completa",
    signalApiFeature4: "Soporte de webhooks para actualizaciones en vivo",
    whiteLabel: "Solución de Marca Blanca",
    whiteLabelDesc: "Lanza tu propia plataforma de predicción IA con tu marca. Diseño totalmente personalizable, tu dominio, tu identidad de marca - impulsado por tecnología OddsFlow.",
    whiteLabelFeature1: "Marca y diseño personalizados",
    whiteLabelFeature2: "Tu propio dominio",
    whiteLabelFeature3: "Panel de administración completo",
    whiteLabelFeature4: "Sistema de gestión de usuarios",
    nativeAds: "Publicidad Nativa",
    nativeAdsDesc: "Monetiza tu tráfico con anuncios nativos integrados. Ubicaciones no intrusivas diseñadas para mejorar la experiencia del usuario mientras maximizas los ingresos.",
    nativeAdsFeature1: "Altas tasas de CPM",
    nativeAdsFeature2: "Ubicaciones no intrusivas",
    nativeAdsFeature3: "Análisis de rendimiento",
    nativeAdsFeature4: "Múltiples formatos de anuncios",
    dataAdvantage: "Ventaja de Datos",
    dataAdvantageDesc: "Nuestros modelos de IA están construidos sobre un análisis de datos multidimensional con extensas pruebas históricas para garantizar la precisión de las predicciones.",
    multiDimensional: "Modelos Multidimensionales",
    multiDimensionalDesc: "Nuestra IA analiza más de 200 variables por partido incluyendo forma del equipo, estadísticas de jugadores, récords cara a cara, condiciones climáticas y movimientos del mercado.",
    backtesting: "Backtesting Histórico",
    backtestingDesc: "Cada modelo se prueba rigurosamente contra más de 10 años de datos históricos en más de 50 ligas para validar la precisión de las predicciones antes de su implementación.",
    flexiblePricing: "Precios Flexibles",
    flexiblePricingDesc: "Elige un modelo de precios que se ajuste a tu negocio. Desde pago por solicitud hasta planes empresariales ilimitados, escalamos con tus necesidades.",
    pricingFeature1: "Modelo de pago por solicitud",
    pricingFeature2: "Suscripciones mensuales",
    pricingFeature3: "Acuerdos empresariales personalizados",
    pricingFeature4: "Descuentos por volumen disponibles",
    contactUs: "Contáctanos",
    contactUsDesc: "¿Listo para integrar OddsFlow en tu plataforma? Nuestro equipo está aquí para ayudarte a encontrar la solución perfecta para las necesidades de tu negocio.",
    getInTouch: "Ponte en Contacto",
    email: "Correo Electrónico",
    footer: "18+ | El juego implica riesgo. Por favor juega responsablemente.",
    allRights: "© 2026 OddsFlow. Todos los derechos reservados.",
    // Why Choose Us
    whyChooseUs: "POR QUÉ ELEGIRNOS",
    whyChooseTitle: "Por qué elegir OddsFlow",
    whyChooseSubtitle: "Experimenta la diferencia con nuestra plataforma impulsada por IA",
    benefit1Title: "99.9% Disponibilidad",
    benefit1Desc: "Nuestra plataforma funciona 24/7 con confiabilidad empresarial",
    benefit2Title: "Datos en Tiempo Real",
    benefit2Desc: "Obtén actualizaciones instantáneas de más de 50 casas de apuestas",
    benefit3Title: "Precisión de IA",
    benefit3Desc: "Nuestros modelos logran más del 78% de precisión en predicciones",
    benefit4Title: "Seguro y Privado",
    benefit4Desc: "Encriptación de nivel bancario protege tus datos",
    benefit5Title: "Soporte 24/7",
    benefit5Desc: "Equipo de soporte experto disponible las 24 horas",
    benefit6Title: "Garantía de Devolución",
    benefit6Desc: "Garantía de devolución de 30 días, sin preguntas",
    // FAQ
    faqTitle: "Preguntas Frecuentes",
    faq1Q: "¿Qué son las predicciones de fútbol con IA?",
    faq1A: "Las predicciones de fútbol con IA son pronósticos estadísticos generados por inteligencia artificial. En OddsFlow, nuestros modelos utilizan datos históricos, rendimiento del equipo y algoritmos avanzados para calcular los resultados más probables de cada partido.",
    faq2Q: "¿Qué tan precisas son sus predicciones?",
    faq2A: "Aunque ninguna predicción está garantizada, nuestros modelos de IA están diseñados para proporcionar probabilidades de alta confianza. Nos enfocamos en la precisión a largo plazo y la optimización continua. Recuerda siempre: las apuestas implican riesgo.",
    faq3Q: "¿Con qué frecuencia se actualizan las predicciones?",
    faq3A: "Las predicciones se actualizan diariamente, con nuevos datos e información de partidos. En caso de noticias de última hora, como lesiones o cambios de alineación, el modelo ajusta automáticamente las probabilidades.",
    faq4Q: "¿Proporcionan consejos de apuestas o solo estadísticas?",
    faq4A: "Nos enfocamos en probabilidades objetivas generadas por IA, no en opiniones personales. Sin embargo, ocasionalmente destacamos selecciones de alta confianza basadas en el modelo de IA para usuarios que buscan información rápida.",
    faq5Q: "¿Son gratuitas estas predicciones?",
    faq5A: "Sí. Nuestras predicciones diarias de apuestas con IA son completamente gratuitas, sin necesidad de registro. Creemos que todos deberían tener acceso a herramientas de apuestas inteligentes basadas en datos.",
    faq6Q: "¿Puedo acceder a sus predicciones en dispositivos móviles?",
    faq6A: "Sí, OddsFlow es totalmente responsive, ofreciendo acceso fluido en escritorio, tablet y smartphone.",
    // Footer
    footerDesc: "Analisis de cuotas de futbol impulsado por IA para predicciones mas inteligentes.",
    product: "Producto",
    liveOdds: "Rendimiento IA",
    popularLeagues: "Ligas Populares",
    communityFooter: "Comunidad",
    globalChat: "Chat Global",
    userPredictions: "Predicciones de Usuarios",
    todayMatches: "Partidos de Hoy",
    company: "Empresa",
    aboutUs: "Sobre Nosotros",
    contact: "Contacto",
    blog: "Blog",
    legal: "Legal",
    termsOfService: "Terminos de Servicio",
    privacyPolicy: "Politica de Privacidad",
    responsibleGaming: "Juego Responsable",
    allRightsReserved: "Todos los derechos reservados.",
    gamblingWarning: "El juego implica riesgo. Por favor juega responsablemente.",
    disclaimer: "Aviso legal: OddsFlow proporciona predicciones impulsadas por IA solo con fines informativos y de entretenimiento. No garantizamos la precision de las predicciones y no somos responsables de ninguna perdida financiera. El juego implica riesgo. Por favor juega responsablemente. Si usted o alguien que conoce tiene un problema con el juego, busque ayuda. Los usuarios deben tener 18+ años.",
  },
  PT: {
    home: "Início",
    predictions: "Previsões",
    leagues: "Ligas",
    performance: "Desempenho IA",
    community: "Comunidade",
    news: "Notícias",
    solution: "Solução",
    pricing: "Preços",
    login: "Entrar",
    getStarted: "Começar",
    heroTitle: "Soluções Empresariais",
    heroSubtitle: "Potencialize sua plataforma com a tecnologia de previsão de futebol baseada em IA da OddsFlow",
    signalApi: "API de Sinais",
    signalApiDesc: "Integre nossas previsões de IA diretamente em sua plataforma com nossa robusta API RESTful. Análise de odds em tempo real, previsões de partidas e cálculos de probabilidade em escala.",
    signalApiFeature1: "Endpoints de previsão em tempo real",
    signalApiFeature2: "SLA de 99.9% de disponibilidade",
    signalApiFeature3: "Documentação abrangente",
    signalApiFeature4: "Suporte a webhooks para atualizações ao vivo",
    whiteLabel: "Solução White Label",
    whiteLabelDesc: "Lance sua própria plataforma de previsão IA com sua marca. Design totalmente personalizável, seu domínio, sua identidade de marca - powered by tecnologia OddsFlow.",
    whiteLabelFeature1: "Marca e design personalizados",
    whiteLabelFeature2: "Seu próprio domínio",
    whiteLabelFeature3: "Painel de administração completo",
    whiteLabelFeature4: "Sistema de gerenciamento de usuários",
    nativeAds: "Publicidade Nativa",
    nativeAdsDesc: "Monetize seu tráfego com anúncios nativos integrados. Posicionamentos não intrusivos projetados para melhorar a experiência do usuário enquanto maximiza a receita.",
    nativeAdsFeature1: "Altas taxas de CPM",
    nativeAdsFeature2: "Posicionamentos não intrusivos",
    nativeAdsFeature3: "Análise de desempenho",
    nativeAdsFeature4: "Múltiplos formatos de anúncios",
    dataAdvantage: "Vantagem de Dados",
    dataAdvantageDesc: "Nossos modelos de IA são construídos com análise de dados multidimensional abrangente e backtesting histórico extensivo para garantir precisão nas previsões.",
    multiDimensional: "Modelos Multidimensionais",
    multiDimensionalDesc: "Nossa IA analisa mais de 200 variáveis por partida, incluindo forma da equipe, estatísticas de jogadores, histórico de confrontos, condições climáticas e movimentos de mercado.",
    backtesting: "Backtesting Histórico",
    backtestingDesc: "Cada modelo é rigorosamente testado contra mais de 10 anos de dados históricos em mais de 50 ligas para validar a precisão das previsões antes da implantação.",
    flexiblePricing: "Preços Flexíveis",
    flexiblePricingDesc: "Escolha um modelo de preços que se adapte ao seu negócio. De pagamento por solicitação a planos empresariais ilimitados, escalamos com suas necessidades.",
    pricingFeature1: "Modelo de pagamento por solicitação",
    pricingFeature2: "Assinaturas mensais",
    pricingFeature3: "Acordos empresariais personalizados",
    pricingFeature4: "Descontos por volume disponíveis",
    contactUs: "Entre em Contato",
    contactUsDesc: "Pronto para integrar o OddsFlow em sua plataforma? Nossa equipe está aqui para ajudá-lo a encontrar a solução perfeita para as necessidades do seu negócio.",
    getInTouch: "Entre em Contato",
    email: "E-mail",
    footer: "18+ | O jogo envolve risco. Por favor, jogue com responsabilidade.",
    allRights: "© 2026 OddsFlow. Todos os direitos reservados.",
    // Why Choose Us
    whyChooseUs: "POR QUE NOS ESCOLHER",
    whyChooseTitle: "Por que escolher a OddsFlow",
    whyChooseSubtitle: "Experimente a diferença com nossa plataforma baseada em IA",
    benefit1Title: "99.9% Disponibilidade",
    benefit1Desc: "Nossa plataforma funciona 24/7 com confiabilidade empresarial",
    benefit2Title: "Dados em Tempo Real",
    benefit2Desc: "Obtenha atualizações instantâneas de mais de 50 casas de apostas",
    benefit3Title: "Precisão de IA",
    benefit3Desc: "Nossos modelos alcançam mais de 78% de precisão nas previsões",
    benefit4Title: "Seguro e Privado",
    benefit4Desc: "Criptografia de nível bancário protege seus dados",
    benefit5Title: "Suporte 24/7",
    benefit5Desc: "Equipe de suporte especializada disponível 24 horas",
    benefit6Title: "Garantia de Reembolso",
    benefit6Desc: "Garantia de reembolso de 30 dias, sem perguntas",
    // FAQ
    faqTitle: "Perguntas Frequentes",
    faq1Q: "O que são previsões de futebol com IA?",
    faq1A: "Previsões de futebol com IA são prognósticos estatísticos gerados por inteligência artificial. Na OddsFlow, nossos modelos usam dados históricos, desempenho da equipe e algoritmos avançados para calcular os resultados mais prováveis de cada partida.",
    faq2Q: "Quão precisas são suas previsões?",
    faq2A: "Embora nenhuma previsão seja garantida, nossos modelos de IA são projetados para fornecer probabilidades de alta confiança. Focamos em precisão a longo prazo e otimização contínua. Lembre-se sempre: apostas envolvem risco.",
    faq3Q: "Com que frequência as previsões são atualizadas?",
    faq3A: "As previsões são atualizadas diariamente, com novos dados e informações de partidas. Em caso de notícias de última hora, como lesões ou mudanças de escalação, o modelo ajusta automaticamente as probabilidades.",
    faq4Q: "Vocês fornecem dicas de apostas ou apenas estatísticas?",
    faq4A: "Focamos em probabilidades objetivas geradas por IA, não em opiniões pessoais. No entanto, ocasionalmente destacamos escolhas de alta confiança baseadas no modelo de IA para usuários que buscam insights rápidos.",
    faq5Q: "Essas previsões são gratuitas?",
    faq5A: "Sim. Nossas previsões diárias de apostas com IA são completamente gratuitas, sem necessidade de cadastro. Acreditamos que todos devem ter acesso a ferramentas de apostas inteligentes baseadas em dados.",
    faq6Q: "Posso acessar suas previsões em dispositivos móveis?",
    faq6A: "Sim, a OddsFlow é totalmente responsiva, oferecendo acesso perfeito em desktop, tablet e smartphone.",
    // Footer
    footerDesc: "Analise de odds de futebol com IA para previsoes mais inteligentes.",
    product: "Produto",
    liveOdds: "Desempenho IA",
    popularLeagues: "Ligas Populares",
    communityFooter: "Comunidade",
    globalChat: "Chat Global",
    userPredictions: "Previsoes de Usuarios",
    todayMatches: "Jogos de Hoje",
    company: "Empresa",
    aboutUs: "Sobre Nos",
    contact: "Contato",
    blog: "Blog",
    legal: "Legal",
    termsOfService: "Termos de Servico",
    privacyPolicy: "Politica de Privacidade",
    responsibleGaming: "Jogo Responsavel",
    allRightsReserved: "Todos os direitos reservados.",
    gamblingWarning: "Apostas envolvem risco. Por favor aposte com responsabilidade.",
    disclaimer: "Aviso legal: OddsFlow fornece previsoes baseadas em IA apenas para fins informativos e de entretenimento. Nao garantimos a precisao das previsoes e nao somos responsaveis por quaisquer perdas financeiras. Apostas envolvem risco. Por favor aposte com responsabilidade. Se voce ou alguem que conhece tem um problema com jogos, procure ajuda. Usuarios devem ter 18+ anos.",
  },
  DE: {
    home: "Startseite",
    predictions: "Vorhersagen",
    leagues: "Ligen",
    performance: "KI-Leistung",
    community: "Community",
    news: "Nachrichten",
    solution: "Lösung",
    pricing: "Preise",
    login: "Anmelden",
    getStarted: "Loslegen",
    heroTitle: "Enterprise-Lösungen",
    heroSubtitle: "Stärken Sie Ihre Plattform mit der KI-gesteuerten Fußballvorhersagetechnologie von OddsFlow",
    signalApi: "Signal-API",
    signalApiDesc: "Integrieren Sie unsere KI-Vorhersagen direkt in Ihre Plattform mit unserer robusten RESTful-API. Echtzeit-Quotenanalyse, Spielvorhersagen und Wahrscheinlichkeitsberechnungen im großen Maßstab.",
    signalApiFeature1: "Echtzeit-Vorhersage-Endpunkte",
    signalApiFeature2: "99,9% Verfügbarkeits-SLA",
    signalApiFeature3: "Umfassende Dokumentation",
    signalApiFeature4: "Webhook-Unterstützung für Live-Updates",
    whiteLabel: "White-Label-Lösung",
    whiteLabelDesc: "Starten Sie Ihre eigene markengebundene KI-Vorhersageplattform. Vollständig anpassbares Design, Ihre Domain, Ihre Markenidentität - powered by OddsFlow-Technologie.",
    whiteLabelFeature1: "Individuelles Branding & Design",
    whiteLabelFeature2: "Ihre eigene Domain",
    whiteLabelFeature3: "Vollständiges Admin-Dashboard",
    whiteLabelFeature4: "Benutzerverwaltungssystem",
    nativeAds: "Native Werbung",
    nativeAdsDesc: "Monetarisieren Sie Ihren Traffic mit nahtlos integrierten nativen Anzeigen. Nicht aufdringliche Platzierungen, die die Benutzererfahrung verbessern und gleichzeitig den Umsatz maximieren.",
    nativeAdsFeature1: "Hohe CPM-Raten",
    nativeAdsFeature2: "Nicht aufdringliche Platzierungen",
    nativeAdsFeature3: "Leistungsanalytik",
    nativeAdsFeature4: "Mehrere Anzeigenformate",
    dataAdvantage: "Datenvorteil",
    dataAdvantageDesc: "Unsere KI-Modelle basieren auf umfassender mehrdimensionaler Datenanalyse mit umfangreichem historischem Backtesting zur Gewährleistung der Vorhersagegenauigkeit.",
    multiDimensional: "Mehrdimensionale Modelle",
    multiDimensionalDesc: "Unsere KI analysiert über 200 Variablen pro Spiel, darunter Teamform, Spielerstatistiken, Head-to-Head-Rekorde, Wetterbedingungen und Marktbewegungen.",
    backtesting: "Historisches Backtesting",
    backtestingDesc: "Jedes Modell wird rigoros gegen über 10 Jahre historischer Daten aus über 50 Ligen getestet, um die Vorhersagegenauigkeit vor der Implementierung zu validieren.",
    flexiblePricing: "Flexible Preisgestaltung",
    flexiblePricingDesc: "Wählen Sie ein Preismodell, das zu Ihrem Unternehmen passt. Von Pay-per-Request bis zu unbegrenzten Enterprise-Plänen - wir skalieren mit Ihren Anforderungen.",
    pricingFeature1: "Pay-per-Request-Modell",
    pricingFeature2: "Monatliche Abonnements",
    pricingFeature3: "Individuelle Enterprise-Vereinbarungen",
    pricingFeature4: "Mengenrabatte verfügbar",
    contactUs: "Kontaktieren Sie uns",
    contactUsDesc: "Bereit, OddsFlow in Ihre Plattform zu integrieren? Unser Team hilft Ihnen gerne, die perfekte Lösung für Ihre Geschäftsanforderungen zu finden.",
    getInTouch: "Kontakt aufnehmen",
    email: "E-Mail",
    footer: "18+ | Glücksspiel birgt Risiken. Bitte spielen Sie verantwortungsvoll.",
    allRights: "© 2026 OddsFlow. Alle Rechte vorbehalten.",
    // Why Choose Us
    whyChooseUs: "WARUM UNS WÄHLEN",
    whyChooseTitle: "Warum OddsFlow wählen",
    whyChooseSubtitle: "Erleben Sie den Unterschied mit unserer KI-gesteuerten Plattform",
    benefit1Title: "99,9% Verfügbarkeit",
    benefit1Desc: "Unsere Plattform läuft 24/7 mit Enterprise-Zuverlässigkeit",
    benefit2Title: "Echtzeit-Daten",
    benefit2Desc: "Erhalten Sie sofortige Updates von über 50 Buchmachern weltweit",
    benefit3Title: "KI-Genauigkeit",
    benefit3Desc: "Unsere Modelle erreichen über 78% Vorhersagegenauigkeit",
    benefit4Title: "Sicher & Privat",
    benefit4Desc: "Bankebene-Verschlüsselung schützt Ihre Daten",
    benefit5Title: "24/7 Support",
    benefit5Desc: "Experten-Support-Team rund um die Uhr verfügbar",
    benefit6Title: "Geld-zurück-Garantie",
    benefit6Desc: "30-Tage Geld-zurück-Garantie, ohne Fragen",
    // FAQ
    faqTitle: "Häufig gestellte Fragen",
    faq1Q: "Was sind KI-Fußballvorhersagen?",
    faq1A: "KI-Fußballvorhersagen sind statistische Prognosen, die von künstlicher Intelligenz erstellt werden. Bei OddsFlow verwenden unsere Modelle historische Daten, Teamleistung und fortschrittliche Algorithmen, um die wahrscheinlichsten Ergebnisse für jedes Fußballspiel zu berechnen.",
    faq2Q: "Wie genau sind Ihre Vorhersagen?",
    faq2A: "Obwohl keine Vorhersage garantiert ist, sind unsere KI-Modelle darauf ausgelegt, Wahrscheinlichkeiten mit hoher Konfidenz zu liefern. Wir konzentrieren uns auf langfristige Genauigkeit und kontinuierliche Optimierung. Denken Sie immer daran: Wetten birgt Risiken.",
    faq3Q: "Wie oft werden die Vorhersagen aktualisiert?",
    faq3A: "Vorhersagen werden täglich mit neuen Daten und Spielinformationen aktualisiert. Bei kurzfristigen Nachrichten wie Verletzungen oder Aufstellungsänderungen passt das Modell die Wahrscheinlichkeiten automatisch an.",
    faq4Q: "Bieten Sie Wetttipps oder nur Statistiken?",
    faq4A: "Wir konzentrieren uns auf objektive KI-generierte Wahrscheinlichkeiten, nicht auf persönliche Meinungen. Gelegentlich heben wir jedoch Auswahlen mit hoher Konfidenz basierend auf dem KI-Modell für Benutzer hervor, die schnelle Einblicke suchen.",
    faq5Q: "Sind diese Vorhersagen kostenlos?",
    faq5A: "Ja. Unsere täglichen KI-Wettvorhersagen sind völlig kostenlos, ohne Registrierung erforderlich. Wir glauben, dass jeder Zugang zu intelligenten, datengesteuerten Wettwerkzeugen haben sollte.",
    faq6Q: "Kann ich auf Ihre Vorhersagen auf mobilen Geräten zugreifen?",
    faq6A: "Ja, OddsFlow ist vollständig mobilfreundlich und bietet nahtlosen Zugriff auf Desktop, Tablet und Smartphone.",
    // Footer
    footerDesc: "KI-gestutzte Fussball-Quotenanalyse fur intelligentere Vorhersagen.",
    product: "Produkt",
    liveOdds: "KI-Leistung",
    popularLeagues: "Beliebte Ligen",
    communityFooter: "Community",
    globalChat: "Globaler Chat",
    userPredictions: "Benutzervorhersagen",
    todayMatches: "Heutige Spiele",
    company: "Unternehmen",
    aboutUs: "Uber Uns",
    contact: "Kontakt",
    blog: "Blog",
    legal: "Rechtliches",
    termsOfService: "Nutzungsbedingungen",
    privacyPolicy: "Datenschutz",
    responsibleGaming: "Verantwortungsvolles Spielen",
    allRightsReserved: "Alle Rechte vorbehalten.",
    gamblingWarning: "Glucksspiel birgt Risiken. Bitte spielen Sie verantwortungsvoll.",
    disclaimer: "Haftungsausschluss: OddsFlow bietet KI-gestutzte Vorhersagen nur zu Informations- und Unterhaltungszwecken. Wir garantieren nicht die Genauigkeit der Vorhersagen und sind nicht verantwortlich fur finanzielle Verluste. Glucksspiel birgt Risiken. Bitte spielen Sie verantwortungsvoll. Wenn Sie oder jemand den Sie kennen ein Glucksspielproblem hat, suchen Sie Hilfe. Benutzer mussen 18+ Jahre alt sein.",
  },
  FR: {
    home: "Accueil",
    predictions: "Prédictions",
    leagues: "Ligues",
    performance: "Performance IA",
    community: "Communauté",
    news: "Actualités",
    solution: "Solution",
    pricing: "Tarifs",
    login: "Connexion",
    getStarted: "Commencer",
    heroTitle: "Solutions Entreprise",
    heroSubtitle: "Propulsez votre plateforme avec la technologie de prédiction football IA d'OddsFlow",
    signalApi: "API de Signaux",
    signalApiDesc: "Intégrez nos prédictions IA directement dans votre plateforme avec notre API RESTful robuste. Analyse de cotes en temps réel, prédictions de matchs et calculs de probabilité à grande échelle.",
    signalApiFeature1: "Endpoints de prédiction en temps réel",
    signalApiFeature2: "SLA de disponibilité 99,9%",
    signalApiFeature3: "Documentation complète",
    signalApiFeature4: "Support webhook pour mises à jour en direct",
    whiteLabel: "Solution Marque Blanche",
    whiteLabelDesc: "Lancez votre propre plateforme de prédiction IA avec votre marque. Design entièrement personnalisable, votre domaine, votre identité de marque - propulsé par la technologie OddsFlow.",
    whiteLabelFeature1: "Marque et design personnalisés",
    whiteLabelFeature2: "Votre propre domaine",
    whiteLabelFeature3: "Tableau de bord admin complet",
    whiteLabelFeature4: "Système de gestion des utilisateurs",
    nativeAds: "Publicité Native",
    nativeAdsDesc: "Monétisez votre trafic avec des publicités natives intégrées. Placements non intrusifs conçus pour améliorer l'expérience utilisateur tout en maximisant les revenus.",
    nativeAdsFeature1: "Taux CPM élevés",
    nativeAdsFeature2: "Placements non intrusifs",
    nativeAdsFeature3: "Analyses de performance",
    nativeAdsFeature4: "Formats publicitaires multiples",
    dataAdvantage: "Avantage Données",
    dataAdvantageDesc: "Nos modèles IA sont construits sur une analyse de données multidimensionnelle complète avec un backtesting historique extensif pour garantir la précision des prédictions.",
    multiDimensional: "Modèles Multidimensionnels",
    multiDimensionalDesc: "Notre IA analyse plus de 200 variables par match, incluant la forme de l'équipe, les statistiques des joueurs, les historiques de confrontations, les conditions météo et les mouvements du marché.",
    backtesting: "Backtesting Historique",
    backtestingDesc: "Chaque modèle est rigoureusement testé contre plus de 10 ans de données historiques sur plus de 50 ligues pour valider la précision des prédictions avant déploiement.",
    flexiblePricing: "Tarification Flexible",
    flexiblePricingDesc: "Choisissez un modèle de tarification adapté à votre entreprise. Du paiement à la demande aux forfaits entreprise illimités, nous évoluons avec vos besoins.",
    pricingFeature1: "Modèle paiement à la demande",
    pricingFeature2: "Abonnements mensuels",
    pricingFeature3: "Accords entreprise personnalisés",
    pricingFeature4: "Remises sur volume disponibles",
    contactUs: "Contactez-nous",
    contactUsDesc: "Prêt à intégrer OddsFlow dans votre plateforme ? Notre équipe est là pour vous aider à trouver la solution parfaite pour vos besoins commerciaux.",
    getInTouch: "Nous Contacter",
    email: "E-mail",
    footer: "18+ | Les jeux d'argent comportent des risques. Jouez de manière responsable.",
    allRights: "© 2026 OddsFlow. Tous droits réservés.",
    // Why Choose Us
    whyChooseUs: "POURQUOI NOUS CHOISIR",
    whyChooseTitle: "Pourquoi choisir OddsFlow",
    whyChooseSubtitle: "Découvrez la différence avec notre plateforme IA",
    benefit1Title: "99,9% Disponibilité",
    benefit1Desc: "Notre plateforme fonctionne 24/7 avec une fiabilité entreprise",
    benefit2Title: "Données en Temps Réel",
    benefit2Desc: "Obtenez des mises à jour instantanées de plus de 50 bookmakers",
    benefit3Title: "Précision IA",
    benefit3Desc: "Nos modèles atteignent plus de 78% de précision de prédiction",
    benefit4Title: "Sécurisé & Privé",
    benefit4Desc: "Un cryptage de niveau bancaire protège vos données",
    benefit5Title: "Support 24/7",
    benefit5Desc: "Équipe de support expert disponible 24 heures sur 24",
    benefit6Title: "Satisfait ou Remboursé",
    benefit6Desc: "Garantie de remboursement de 30 jours, sans questions",
    // FAQ
    faqTitle: "Questions Fréquentes",
    faq1Q: "Que sont les prédictions de football IA?",
    faq1A: "Les prédictions de football IA sont des prévisions statistiques générées par l'intelligence artificielle. Chez OddsFlow, nos modèles utilisent des données historiques, les performances des équipes et des algorithmes avancés pour calculer les résultats les plus probables de chaque match.",
    faq2Q: "Quelle est la précision de vos prédictions?",
    faq2A: "Bien qu'aucune prédiction ne soit garantie, nos modèles IA sont conçus pour fournir des probabilités de haute confiance. Nous nous concentrons sur la précision à long terme et l'optimisation continue. N'oubliez jamais: les paris comportent des risques.",
    faq3Q: "À quelle fréquence les prédictions sont-elles mises à jour?",
    faq3A: "Les prédictions sont mises à jour quotidiennement avec de nouvelles données et informations sur les matchs. En cas de nouvelles de dernière minute, comme des blessures ou des changements de composition, le modèle ajuste automatiquement les probabilités.",
    faq4Q: "Fournissez-vous des conseils de paris ou juste des statistiques?",
    faq4A: "Nous nous concentrons sur des probabilités objectives générées par l'IA, pas sur des opinions personnelles. Cependant, nous pouvons occasionnellement mettre en avant des choix de haute confiance basés sur le modèle IA pour les utilisateurs recherchant des insights rapides.",
    faq5Q: "Ces prédictions sont-elles gratuites?",
    faq5A: "Oui. Nos prédictions de paris IA quotidiennes sont entièrement gratuites, sans inscription requise. Nous croyons que tout le monde devrait avoir accès à des outils de paris intelligents basés sur les données.",
    faq6Q: "Puis-je accéder à vos prédictions sur mobile?",
    faq6A: "Oui, OddsFlow est entièrement responsive, offrant un accès fluide sur ordinateur, tablette et smartphone.",
    // Footer
    footerDesc: "Analyse de cotes de football propulsee par l'IA pour des predictions plus intelligentes.",
    product: "Produit",
    liveOdds: "Performance IA",
    popularLeagues: "Ligues Populaires",
    communityFooter: "Communaute",
    globalChat: "Chat Global",
    userPredictions: "Predictions Utilisateurs",
    todayMatches: "Matchs du Jour",
    company: "Entreprise",
    aboutUs: "A Propos",
    contact: "Contact",
    blog: "Blog",
    legal: "Mentions Legales",
    termsOfService: "Conditions d'Utilisation",
    privacyPolicy: "Politique de Confidentialite",
    responsibleGaming: "Jeu Responsable",
    allRightsReserved: "Tous droits reserves.",
    gamblingWarning: "Le jeu comporte des risques. Veuillez jouer de maniere responsable.",
    disclaimer: "Avertissement: OddsFlow fournit des predictions basees sur l'IA a des fins d'information et de divertissement uniquement. Nous ne garantissons pas l'exactitude des predictions et ne sommes pas responsables des pertes financieres. Le jeu comporte des risques. Veuillez jouer de maniere responsable. Si vous ou quelqu'un que vous connaissez a un probleme de jeu, veuillez chercher de l'aide. Les utilisateurs doivent avoir 18+ ans.",
  },
  JA: {
    home: "ホーム",
    predictions: "予測",
    leagues: "リーグ",
    performance: "AIパフォーマンス",
    community: "コミュニティ",
    news: "ニュース",
    solution: "ソリューション",
    pricing: "料金",
    login: "ログイン",
    getStarted: "始める",
    heroTitle: "エンタープライズソリューション",
    heroSubtitle: "OddsFlowのAI駆動サッカー予測技術でプラットフォームを強化",
    signalApi: "シグナルAPI",
    signalApiDesc: "堅牢なRESTful APIで、AI予測をプラットフォームに直接統合。リアルタイムオッズ分析、試合予測、確率計算を大規模に提供。",
    signalApiFeature1: "リアルタイム予測エンドポイント",
    signalApiFeature2: "99.9%稼働率SLA",
    signalApiFeature3: "包括的なドキュメント",
    signalApiFeature4: "ライブ更新用Webhookサポート",
    whiteLabel: "ホワイトラベルソリューション",
    whiteLabelDesc: "独自ブランドのAI予測プラットフォームを立ち上げ。完全カスタマイズ可能なデザイン、独自ドメイン、ブランドアイデンティティ - OddsFlow技術で実現。",
    whiteLabelFeature1: "カスタムブランディング＆デザイン",
    whiteLabelFeature2: "独自ドメイン",
    whiteLabelFeature3: "フル管理ダッシュボード",
    whiteLabelFeature4: "ユーザー管理システム",
    nativeAds: "ネイティブ広告",
    nativeAdsDesc: "シームレスに統合されたネイティブ広告でトラフィックを収益化。ユーザー体験を向上させながら収益を最大化する非侵入型配置。",
    nativeAdsFeature1: "高いCPMレート",
    nativeAdsFeature2: "非侵入型配置",
    nativeAdsFeature3: "パフォーマンス分析",
    nativeAdsFeature4: "複数の広告フォーマット",
    dataAdvantage: "データアドバンテージ",
    dataAdvantageDesc: "当社のAIモデルは、予測精度を確保するための広範な過去データバックテストを含む包括的な多次元データ分析に基づいて構築されています。",
    multiDimensional: "多次元モデル",
    multiDimensionalDesc: "当社のAIは、チームの調子、選手統計、対戦成績、天候条件、市場動向を含む試合ごとに200以上の変数を分析します。",
    backtesting: "過去データバックテスト",
    backtestingDesc: "各モデルは、デプロイ前に予測精度を検証するため、50以上のリーグの10年以上の過去データに対して厳密にテストされます。",
    flexiblePricing: "柔軟な価格設定",
    flexiblePricingDesc: "ビジネスに合った価格モデルをお選びください。リクエスト単位から無制限のエンタープライズプランまで、お客様のニーズに合わせてスケールします。",
    pricingFeature1: "リクエスト単位モデル",
    pricingFeature2: "月額サブスクリプション",
    pricingFeature3: "カスタムエンタープライズ契約",
    pricingFeature4: "ボリューム割引あり",
    contactUs: "お問い合わせ",
    contactUsDesc: "OddsFlowをプラットフォームに統合する準備はできましたか？お客様のビジネスニーズに最適なソリューションを見つけるお手伝いをいたします。",
    getInTouch: "お問い合わせ",
    email: "メール",
    footer: "18歳以上 | ギャンブルにはリスクが伴います。責任を持ってプレイしてください。",
    allRights: "© 2026 OddsFlow. 全著作権所有。",
    // Why Choose Us
    whyChooseUs: "選ばれる理由",
    whyChooseTitle: "なぜOddsFlowを選ぶのか",
    whyChooseSubtitle: "AI搭載プラットフォームで違いを体験してください",
    benefit1Title: "99.9%稼働率",
    benefit1Desc: "エンタープライズグレードの信頼性で24時間365日稼働",
    benefit2Title: "リアルタイムデータ",
    benefit2Desc: "世界50以上のブックメーカーから即座に更新",
    benefit3Title: "AI精度",
    benefit3Desc: "当社のモデルは78%以上の予測精度を達成",
    benefit4Title: "安全＆プライベート",
    benefit4Desc: "銀行レベルの暗号化でデータを保護",
    benefit5Title: "24/7サポート",
    benefit5Desc: "専門サポートチームが24時間対応",
    benefit6Title: "返金保証",
    benefit6Desc: "30日間の返金保証、質問なし",
    // FAQ
    faqTitle: "よくある質問",
    faq1Q: "AIサッカー予測とは何ですか？",
    faq1A: "AIサッカー予測は、人工知能によって生成される統計的予測です。OddsFlowでは、過去のデータ、チームのパフォーマンス、高度なアルゴリズムを使用して、各サッカー試合の最も可能性の高い結果を計算します。",
    faq2Q: "予測はどの程度正確ですか？",
    faq2A: "予測は保証されるものではありませんが、当社のAIモデルは高い信頼度の確率を提供するように設計されています。長期的な精度と継続的な最適化に焦点を当てています。常に覚えておいてください：ベッティングにはリスクが伴います。",
    faq3Q: "予測はどのくらいの頻度で更新されますか？",
    faq3A: "予測は毎日、新しいデータと試合情報で更新されます。怪我やラインアップ変更などの最新ニュースがある場合、モデルは自動的に確率を調整します。",
    faq4Q: "ベッティングのヒントを提供しますか、それとも統計だけですか？",
    faq4A: "私たちはAIが生成した客観的な確率に焦点を当てており、個人的な意見ではありません。ただし、迅速な洞察を求めるユーザー向けに、AIモデルに基づいた高信頼度の選択を時折ハイライトすることがあります。",
    faq5Q: "これらの予測は無料で利用できますか？",
    faq5A: "はい。毎日のAIベッティング予測は完全に無料で、サインアップは不要です。誰もがインテリジェントでデータ駆動型のベッティングツールにアクセスできるべきだと考えています。",
    faq6Q: "モバイルデバイスで予測にアクセスできますか？",
    faq6A: "はい、OddsFlowは完全にモバイル対応で、デスクトップ、タブレット、スマートフォンでシームレスにアクセスできます。",
    // Footer
    footerDesc: "よりスマートな予測のためのAI駆動フットボールオッズ分析。",
    product: "製品",
    liveOdds: "AIパフォーマンス",
    popularLeagues: "人気リーグ",
    communityFooter: "コミュニティ",
    globalChat: "グローバルチャット",
    userPredictions: "ユーザー予測",
    todayMatches: "今日の試合",
    company: "会社",
    aboutUs: "私たちについて",
    contact: "お問い合わせ",
    blog: "ブログ",
    legal: "法的情報",
    termsOfService: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    responsibleGaming: "責任あるギャンブル",
    allRightsReserved: "全著作権所有。",
    gamblingWarning: "ギャンブルにはリスクが伴います。責任を持ってお楽しみください。",
    disclaimer: "免責事項: OddsFlowは情報および娯楽目的のみでAI駆動の予測を提供しています。予測の正確性を保証せず、いかなる財務損失についても責任を負いません。ギャンブルにはリスクが伴います。責任を持ってお楽しみください。あなたまたはあなたの知人がギャンブル問題を抱えている場合は、助けを求めてください。ユーザーは18歳以上である必要があります。",
  },
  KO: {
    home: "홈",
    predictions: "예측",
    leagues: "리그",
    performance: "AI 성능",
    community: "커뮤니티",
    news: "뉴스",
    solution: "솔루션",
    pricing: "가격",
    login: "로그인",
    getStarted: "시작하기",
    heroTitle: "엔터프라이즈 솔루션",
    heroSubtitle: "OddsFlow의 AI 기반 축구 예측 기술로 플랫폼을 강화하세요",
    signalApi: "시그널 API",
    signalApiDesc: "강력한 RESTful API로 AI 예측을 플랫폼에 직접 통합하세요. 실시간 배당률 분석, 경기 예측, 확률 계산을 대규모로 제공합니다.",
    signalApiFeature1: "실시간 예측 엔드포인트",
    signalApiFeature2: "99.9% 가동률 SLA",
    signalApiFeature3: "포괄적인 문서화",
    signalApiFeature4: "실시간 업데이트용 웹훅 지원",
    whiteLabel: "화이트 라벨 솔루션",
    whiteLabelDesc: "자체 브랜드 AI 예측 플랫폼을 출시하세요. 완전히 커스터마이징 가능한 디자인, 자체 도메인, 브랜드 아이덴티티 - OddsFlow 기술로 구동.",
    whiteLabelFeature1: "맞춤 브랜딩 & 디자인",
    whiteLabelFeature2: "자체 도메인",
    whiteLabelFeature3: "전체 관리자 대시보드",
    whiteLabelFeature4: "사용자 관리 시스템",
    nativeAds: "네이티브 광고",
    nativeAdsDesc: "원활하게 통합된 네이티브 광고로 트래픽을 수익화하세요. 사용자 경험을 향상시키면서 수익을 극대화하는 비침해적 배치.",
    nativeAdsFeature1: "높은 CPM 요율",
    nativeAdsFeature2: "비침해적 배치",
    nativeAdsFeature3: "성과 분석",
    nativeAdsFeature4: "다양한 광고 형식",
    dataAdvantage: "데이터 우위",
    dataAdvantageDesc: "당사의 AI 모델은 예측 정확도를 보장하기 위해 광범위한 과거 데이터 백테스팅을 포함한 포괄적인 다차원 데이터 분석을 기반으로 구축됩니다.",
    multiDimensional: "다차원 모델",
    multiDimensionalDesc: "당사 AI는 팀 상태, 선수 통계, 상대 전적, 기상 조건, 시장 동향을 포함하여 경기당 200개 이상의 변수를 분석합니다.",
    backtesting: "과거 데이터 백테스팅",
    backtestingDesc: "각 모델은 배포 전 예측 정확도를 검증하기 위해 50개 이상의 리그에서 10년 이상의 과거 데이터에 대해 엄격하게 테스트됩니다.",
    flexiblePricing: "유연한 가격 책정",
    flexiblePricingDesc: "비즈니스에 맞는 가격 모델을 선택하세요. 요청당 결제부터 무제한 엔터프라이즈 플랜까지, 필요에 따라 확장합니다.",
    pricingFeature1: "요청당 결제 모델",
    pricingFeature2: "월간 구독",
    pricingFeature3: "맞춤 엔터프라이즈 계약",
    pricingFeature4: "대량 할인 가능",
    contactUs: "문의하기",
    contactUsDesc: "OddsFlow를 플랫폼에 통합할 준비가 되셨나요? 비즈니스 요구에 맞는 완벽한 솔루션을 찾는 데 도움을 드리겠습니다.",
    getInTouch: "연락하기",
    email: "이메일",
    footer: "18세 이상 | 도박에는 위험이 따릅니다. 책임감 있게 플레이하세요.",
    allRights: "© 2026 OddsFlow. 모든 권리 보유.",
    // Why Choose Us
    whyChooseUs: "선택하는 이유",
    whyChooseTitle: "왜 OddsFlow를 선택하나요",
    whyChooseSubtitle: "AI 기반 플랫폼으로 차이를 경험하세요",
    benefit1Title: "99.9% 가동률",
    benefit1Desc: "엔터프라이즈급 안정성으로 24/7 운영",
    benefit2Title: "실시간 데이터",
    benefit2Desc: "전 세계 50개 이상의 북메이커에서 즉시 업데이트",
    benefit3Title: "AI 정확도",
    benefit3Desc: "우리 모델은 78% 이상의 예측 정확도 달성",
    benefit4Title: "안전 & 개인정보 보호",
    benefit4Desc: "은행 수준의 암호화로 데이터 보호",
    benefit5Title: "24/7 지원",
    benefit5Desc: "전문 지원팀이 24시간 대기",
    benefit6Title: "환불 보장",
    benefit6Desc: "30일 환불 보장, 질문 없음",
    // FAQ
    faqTitle: "자주 묻는 질문",
    faq1Q: "AI 축구 예측이란 무엇인가요?",
    faq1A: "AI 축구 예측은 인공지능이 생성하는 통계적 예측입니다. OddsFlow에서 우리의 모델은 과거 데이터, 팀 성적, 고급 알고리즘을 사용하여 각 축구 경기의 가장 가능성 있는 결과를 계산합니다.",
    faq2Q: "예측은 얼마나 정확한가요?",
    faq2A: "어떤 예측도 보장되지 않지만, 우리의 AI 모델은 높은 신뢰도의 확률을 제공하도록 설계되었습니다. 장기적인 정확도와 지속적인 최적화에 집중합니다. 항상 기억하세요: 베팅에는 위험이 따릅니다.",
    faq3Q: "예측은 얼마나 자주 업데이트되나요?",
    faq3A: "예측은 새로운 데이터와 경기 정보로 매일 업데이트됩니다. 부상이나 라인업 변경과 같은 긴급 뉴스의 경우, 모델은 자동으로 확률을 조정합니다.",
    faq4Q: "베팅 팁을 제공하나요 아니면 통계만 제공하나요?",
    faq4A: "우리는 개인적인 의견이 아닌 AI가 생성한 객관적인 확률에 중점을 둡니다. 그러나 빠른 인사이트를 원하는 사용자를 위해 AI 모델을 기반으로 한 높은 신뢰도의 선택을 가끔 강조할 수 있습니다.",
    faq5Q: "이 예측은 무료로 이용할 수 있나요?",
    faq5A: "네. 우리의 일일 AI 베팅 예측은 완전히 무료이며, 가입이 필요 없습니다. 모든 사람이 지능적이고 데이터 기반의 베팅 도구에 접근할 수 있어야 한다고 믿습니다.",
    faq6Q: "모바일 기기에서 예측에 접근할 수 있나요?",
    faq6A: "네, OddsFlow는 완전히 모바일 반응형으로, 데스크톱, 태블릿, 스마트폰에서 원활하게 접근할 수 있습니다.",
    // Footer
    footerDesc: "더 스마트한 예측을 위한 AI 기반 축구 배당률 분석.",
    product: "제품",
    liveOdds: "AI 성능",
    popularLeagues: "인기 리그",
    communityFooter: "커뮤니티",
    globalChat: "글로벌 채팅",
    userPredictions: "사용자 예측",
    todayMatches: "오늘 경기",
    company: "회사",
    aboutUs: "회사 소개",
    contact: "문의하기",
    blog: "블로그",
    legal: "법적 정보",
    termsOfService: "서비스 약관",
    privacyPolicy: "개인정보 처리방침",
    responsibleGaming: "책임감 있는 게임",
    allRightsReserved: "모든 권리 보유.",
    gamblingWarning: "도박에는 위험이 따릅니다. 책임감 있게 즐기세요.",
    disclaimer: "면책조항: OddsFlow는 정보 및 오락 목적으로만 AI 기반 예측을 제공합니다. 예측의 정확성을 보장하지 않으며 어떠한 재정적 손실에 대해서도 책임지지 않습니다. 도박에는 위험이 따릅니다. 책임감 있게 즐기세요. 본인 또는 아는 사람이 도박 문제가 있다면 도움을 구하세요. 사용자는 18세 이상이어야 합니다.",
  },
  '中文': {
    home: "首页",
    predictions: "预测",
    leagues: "联赛",
    performance: "AI表现",
    community: "社区",
    news: "新闻",
    solution: "解决方案",
    pricing: "价格",
    login: "登录",
    getStarted: "开始使用",
    heroTitle: "企业解决方案",
    heroSubtitle: "使用OddsFlow的AI驱动足球预测技术为您的平台赋能",
    signalApi: "信号API",
    signalApiDesc: "通过我们强大的RESTful API将AI预测直接集成到您的平台中。大规模提供实时赔率分析、比赛预测和概率计算。",
    signalApiFeature1: "实时预测接口",
    signalApiFeature2: "99.9%可用性SLA",
    signalApiFeature3: "全面的文档",
    signalApiFeature4: "支持实时更新的Webhook",
    whiteLabel: "白标解决方案",
    whiteLabelDesc: "推出您自己品牌的AI预测平台。完全可定制的设计、您的域名、您的品牌标识 - 由OddsFlow技术驱动。",
    whiteLabelFeature1: "定制品牌和设计",
    whiteLabelFeature2: "您自己的域名",
    whiteLabelFeature3: "完整的管理仪表板",
    whiteLabelFeature4: "用户管理系统",
    nativeAds: "原生广告",
    nativeAdsDesc: "通过无缝集成的原生广告将您的流量变现。非侵入式展示位置旨在提升用户体验的同时最大化收入。",
    nativeAdsFeature1: "高CPM费率",
    nativeAdsFeature2: "非侵入式展示",
    nativeAdsFeature3: "效果分析",
    nativeAdsFeature4: "多种广告格式",
    dataAdvantage: "数据优势",
    dataAdvantageDesc: "我们的AI模型建立在全面的多维数据分析和广泛的历史回测基础上，以确保预测准确性。",
    multiDimensional: "多维模型",
    multiDimensionalDesc: "我们的AI每场比赛分析200多个变量，包括球队状态、球员统计、交锋记录、天气条件和市场走势。",
    backtesting: "历史回测",
    backtestingDesc: "每个模型都经过严格测试，使用50多个联赛10多年的历史数据来验证部署前的预测准确性。",
    flexiblePricing: "灵活定价",
    flexiblePricingDesc: "选择适合您业务的定价模式。从按请求付费到无限企业计划，我们随您的需求扩展。",
    pricingFeature1: "按请求付费模式",
    pricingFeature2: "月度订阅",
    pricingFeature3: "定制企业协议",
    pricingFeature4: "提供批量折扣",
    contactUs: "联系我们",
    contactUsDesc: "准备好将OddsFlow集成到您的平台了吗？我们的团队随时帮助您找到适合您业务需求的完美解决方案。",
    getInTouch: "取得联系",
    email: "电子邮件",
    footer: "18+ | 博彩有风险，请理性投注。",
    allRights: "© 2026 OddsFlow. 保留所有权利。",
    // Why Choose Us
    whyChooseUs: "为什么选择我们",
    whyChooseTitle: "为什么选择 OddsFlow",
    whyChooseSubtitle: "体验我们AI驱动平台的不同之处",
    benefit1Title: "99.9% 在线率",
    benefit1Desc: "我们的平台以企业级可靠性全天候运行",
    benefit2Title: "实时数据",
    benefit2Desc: "从全球50多家博彩公司获取即时更新",
    benefit3Title: "AI准确率",
    benefit3Desc: "我们的模型实现78%以上的预测准确率",
    benefit4Title: "安全私密",
    benefit4Desc: "银行级加密保护您的数据",
    benefit5Title: "24/7 支持",
    benefit5Desc: "专业支持团队全天候在线",
    benefit6Title: "退款保证",
    benefit6Desc: "30天退款保证，无需任何理由",
    // FAQ
    faqTitle: "常见问题",
    faq1Q: "什么是AI足球预测？",
    faq1A: "AI足球预测是由人工智能生成的统计预测。在OddsFlow，我们的模型使用历史数据、球队表现和高级算法来计算每场足球比赛最可能的结果。",
    faq2Q: "你们的预测有多准确？",
    faq2A: "虽然没有任何预测是有保证的，但我们的AI模型旨在提供高置信度的概率。我们专注于长期准确性和持续优化。请始终记住：投注涉及风险。",
    faq3Q: "预测多久更新一次？",
    faq3A: "预测每天更新，包含新数据和比赛信息。在突发新闻情况下，如伤病或阵容变化，模型会自动调整概率。",
    faq4Q: "你们提供投注建议还是只提供统计数据？",
    faq4A: "我们专注于AI生成的客观概率，而非个人观点。然而，我们可能会偶尔为寻求快速洞察的用户突出显示基于AI模型的高置信度选择。",
    faq5Q: "这些预测可以免费使用吗？",
    faq5A: "是的。我们的每日AI投注预测完全免费，无需注册。我们相信每个人都应该能够访问智能的、数据驱动的投注工具。",
    faq6Q: "我可以在移动设备上访问你们的预测吗？",
    faq6A: "是的，OddsFlow完全适配移动端，可在台式机、平板电脑和智能手机上无缝访问。",
    // Footer
    footerDesc: "AI 驱动的足球赔率分析，助您做出更明智的预测。",
    product: "产品",
    liveOdds: "AI表现",
    popularLeagues: "热门联赛",
    communityFooter: "社区",
    globalChat: "全球聊天",
    userPredictions: "用户预测",
    todayMatches: "今日比赛",
    company: "公司",
    aboutUs: "关于我们",
    contact: "联系我们",
    blog: "博客",
    legal: "法律",
    termsOfService: "服务条款",
    privacyPolicy: "隐私政策",
    responsibleGaming: "负责任博彩",
    allRightsReserved: "版权所有。",
    gamblingWarning: "博彩有风险，请理性投注。",
    disclaimer: "免责声明：OddsFlow 提供的 AI 预测仅供参考和娱乐目的。我们不保证预测的准确性，也不对任何财务损失负责。博彩有风险，请理性投注。如果您或您认识的人有赌博问题，请寻求帮助。用户必须年满 18 岁。",
  },
  '繁體': {
    home: "首頁",
    predictions: "預測",
    leagues: "聯賽",
    performance: "AI表現",
    community: "社區",
    news: "新聞",
    solution: "解決方案",
    pricing: "價格",
    login: "登入",
    getStarted: "開始使用",
    heroTitle: "企業解決方案",
    heroSubtitle: "使用OddsFlow的AI驅動足球預測技術為您的平台賦能",
    signalApi: "信號API",
    signalApiDesc: "通過我們強大的RESTful API將AI預測直接集成到您的平台中。大規模提供實時賠率分析、比賽預測和概率計算。",
    signalApiFeature1: "實時預測接口",
    signalApiFeature2: "99.9%可用性SLA",
    signalApiFeature3: "全面的文檔",
    signalApiFeature4: "支持實時更新的Webhook",
    whiteLabel: "白標解決方案",
    whiteLabelDesc: "推出您自己品牌的AI預測平台。完全可定制的設計、您的域名、您的品牌標識 - 由OddsFlow技術驅動。",
    whiteLabelFeature1: "定制品牌和設計",
    whiteLabelFeature2: "您自己的域名",
    whiteLabelFeature3: "完整的管理儀表板",
    whiteLabelFeature4: "用戶管理系統",
    nativeAds: "原生廣告",
    nativeAdsDesc: "通過無縫集成的原生廣告將您的流量變現。非侵入式展示位置旨在提升用戶體驗的同時最大化收入。",
    nativeAdsFeature1: "高CPM費率",
    nativeAdsFeature2: "非侵入式展示",
    nativeAdsFeature3: "效果分析",
    nativeAdsFeature4: "多種廣告格式",
    dataAdvantage: "數據優勢",
    dataAdvantageDesc: "我們的AI模型建立在全面的多維數據分析和廣泛的歷史回測基礎上，以確保預測準確性。",
    multiDimensional: "多維模型",
    multiDimensionalDesc: "我們的AI每場比賽分析200多個變量，包括球隊狀態、球員統計、交鋒記錄、天氣條件和市場走勢。",
    backtesting: "歷史回測",
    backtestingDesc: "每個模型都經過嚴格測試，使用50多個聯賽10多年的歷史數據來驗證部署前的預測準確性。",
    flexiblePricing: "靈活定價",
    flexiblePricingDesc: "選擇適合您業務的定價模式。從按請求付費到無限企業計劃，我們隨您的需求擴展。",
    pricingFeature1: "按請求付費模式",
    pricingFeature2: "月度訂閱",
    pricingFeature3: "定制企業協議",
    pricingFeature4: "提供批量折扣",
    contactUs: "聯繫我們",
    contactUsDesc: "準備好將OddsFlow集成到您的平台了嗎？我們的團隊隨時幫助您找到適合您業務需求的完美解決方案。",
    getInTouch: "取得聯繫",
    email: "電子郵件",
    footer: "18+ | 博彩有風險，請理性投注。",
    allRights: "© 2026 OddsFlow. 保留所有權利。",
    // Why Choose Us
    whyChooseUs: "為什麼選擇我們",
    whyChooseTitle: "為什麼選擇 OddsFlow",
    whyChooseSubtitle: "體驗我們AI驅動平台的不同之處",
    benefit1Title: "99.9% 在線率",
    benefit1Desc: "我們的平台以企業級可靠性全天候運行",
    benefit2Title: "實時數據",
    benefit2Desc: "從全球50多家博彩公司獲取即時更新",
    benefit3Title: "AI準確率",
    benefit3Desc: "我們的模型實現78%以上的預測準確率",
    benefit4Title: "安全私密",
    benefit4Desc: "銀行級加密保護您的數據",
    benefit5Title: "24/7 支持",
    benefit5Desc: "專業支持團隊全天候在線",
    benefit6Title: "退款保證",
    benefit6Desc: "30天退款保證，無需任何理由",
    // FAQ
    faqTitle: "常見問題",
    faq1Q: "什麼是AI足球預測？",
    faq1A: "AI足球預測是由人工智能生成的統計預測。在OddsFlow，我們的模型使用歷史數據、球隊表現和高級算法來計算每場足球比賽最可能的結果。",
    faq2Q: "你們的預測有多準確？",
    faq2A: "雖然沒有任何預測是有保證的，但我們的AI模型旨在提供高置信度的概率。我們專注於長期準確性和持續優化。請始終記住：投注涉及風險。",
    faq3Q: "預測多久更新一次？",
    faq3A: "預測每天更新，包含新數據和比賽信息。在突發新聞情況下，如傷病或陣容變化，模型會自動調整概率。",
    faq4Q: "你們提供投注建議還是只提供統計數據？",
    faq4A: "我們專注於AI生成的客觀概率，而非個人觀點。然而，我們可能會偶爾為尋求快速洞察的用戶突出顯示基於AI模型的高置信度選擇。",
    faq5Q: "這些預測可以免費使用嗎？",
    faq5A: "是的。我們的每日AI投注預測完全免費，無需註冊。我們相信每個人都應該能夠訪問智能的、數據驅動的投注工具。",
    faq6Q: "我可以在移動設備上訪問你們的預測嗎？",
    faq6A: "是的，OddsFlow完全適配移動端，可在台式機、平板電腦和智能手機上無縫訪問。",
    // Footer
    footerDesc: "AI 驅動的足球賠率分析，助您做出更明智的預測。",
    product: "產品",
    liveOdds: "AI表現",
    popularLeagues: "熱門聯賽",
    communityFooter: "社區",
    globalChat: "全球聊天",
    userPredictions: "用戶預測",
    todayMatches: "今日比賽",
    company: "公司",
    aboutUs: "關於我們",
    contact: "聯繫我們",
    blog: "博客",
    legal: "法律",
    termsOfService: "服務條款",
    privacyPolicy: "隱私政策",
    responsibleGaming: "負責任博彩",
    allRightsReserved: "版權所有。",
    gamblingWarning: "博彩有風險，請理性投注。",
    disclaimer: "免責聲明：OddsFlow 提供的 AI 預測僅供參考和娛樂目的。我們不保證預測的準確性，也不對任何財務損失負責。博彩有風險，請理性投注。如果您或您認識的人有賭博問題，請尋求幫助。用戶必須年滿 18 歲。",
  },
  ID: {
    home: "Beranda",
    predictions: "Prediksi",
    leagues: "Liga",
    performance: "Performa AI",
    community: "Komunitas",
    news: "Berita",
    solution: "Solusi",
    pricing: "Harga",
    login: "Masuk",
    getStarted: "Mulai",
    heroTitle: "Solusi Enterprise",
    heroSubtitle: "Tingkatkan platform Anda dengan teknologi prediksi sepak bola berbasis AI dari OddsFlow",
    signalApi: "Signal API",
    signalApiDesc: "Integrasikan prediksi AI kami langsung ke platform Anda dengan API RESTful yang andal. Analisis odds real-time, prediksi pertandingan, dan perhitungan probabilitas dalam skala besar.",
    signalApiFeature1: "Endpoint prediksi real-time",
    signalApiFeature2: "SLA ketersediaan 99,9%",
    signalApiFeature3: "Dokumentasi lengkap",
    signalApiFeature4: "Dukungan webhook untuk pembaruan langsung",
    whiteLabel: "Solusi White Label",
    whiteLabelDesc: "Luncurkan platform prediksi AI dengan merek Anda sendiri. Desain yang sepenuhnya dapat disesuaikan, domain Anda, identitas merek Anda - didukung oleh teknologi OddsFlow.",
    whiteLabelFeature1: "Branding & desain kustom",
    whiteLabelFeature2: "Domain Anda sendiri",
    whiteLabelFeature3: "Dashboard admin lengkap",
    whiteLabelFeature4: "Sistem manajemen pengguna",
    nativeAds: "Iklan Native",
    nativeAdsDesc: "Monetisasi lalu lintas Anda dengan iklan native yang terintegrasi mulus. Penempatan non-intrusif yang dirancang untuk meningkatkan pengalaman pengguna sambil memaksimalkan pendapatan.",
    nativeAdsFeature1: "Tarif CPM tinggi",
    nativeAdsFeature2: "Penempatan non-intrusif",
    nativeAdsFeature3: "Analitik performa",
    nativeAdsFeature4: "Berbagai format iklan",
    dataAdvantage: "Keunggulan Data",
    dataAdvantageDesc: "Model AI kami dibangun di atas analisis data multi-dimensi yang komprehensif dengan backtesting historis yang ekstensif untuk memastikan akurasi prediksi.",
    multiDimensional: "Model Multi-Dimensi",
    multiDimensionalDesc: "AI kami menganalisis 200+ variabel per pertandingan termasuk performa tim, statistik pemain, catatan head-to-head, kondisi cuaca, dan pergerakan pasar.",
    backtesting: "Backtesting Historis",
    backtestingDesc: "Setiap model diuji secara ketat terhadap data historis 10+ tahun di 50+ liga untuk memvalidasi akurasi prediksi sebelum deployment.",
    flexiblePricing: "Harga Fleksibel",
    flexiblePricingDesc: "Pilih model harga yang sesuai dengan bisnis Anda. Dari bayar-per-permintaan hingga paket enterprise tak terbatas, kami berkembang sesuai kebutuhan Anda.",
    pricingFeature1: "Model bayar-per-permintaan",
    pricingFeature2: "Langganan bulanan",
    pricingFeature3: "Kesepakatan enterprise kustom",
    pricingFeature4: "Diskon volume tersedia",
    contactUs: "Hubungi Kami",
    contactUsDesc: "Siap mengintegrasikan OddsFlow ke platform Anda? Tim kami siap membantu Anda menemukan solusi sempurna untuk kebutuhan bisnis Anda.",
    getInTouch: "Hubungi Kami",
    email: "Email",
    footer: "18+ | Perjudian melibatkan risiko. Harap bertaruh dengan bijak.",
    allRights: "© 2026 OddsFlow. Hak cipta dilindungi.",
    // Why Choose Us
    whyChooseUs: "MENGAPA MEMILIH KAMI",
    whyChooseTitle: "Mengapa Memilih OddsFlow",
    whyChooseSubtitle: "Rasakan perbedaan dengan platform AI kami",
    benefit1Title: "99.9% Uptime",
    benefit1Desc: "Platform kami berjalan 24/7 dengan keandalan enterprise",
    benefit2Title: "Data Real-time",
    benefit2Desc: "Dapatkan pembaruan instan dari 50+ bandar taruhan",
    benefit3Title: "Akurasi AI",
    benefit3Desc: "Model kami mencapai akurasi prediksi 78%+",
    benefit4Title: "Aman & Privat",
    benefit4Desc: "Enkripsi tingkat bank melindungi data Anda",
    benefit5Title: "Dukungan 24/7",
    benefit5Desc: "Tim dukungan ahli tersedia sepanjang waktu",
    benefit6Title: "Jaminan Uang Kembali",
    benefit6Desc: "Jaminan uang kembali 30 hari, tanpa pertanyaan",
    // FAQ
    faqTitle: "Pertanyaan yang Sering Diajukan",
    faq1Q: "Apa itu prediksi sepak bola AI?",
    faq1A: "Prediksi sepak bola AI adalah perkiraan statistik yang dihasilkan oleh kecerdasan buatan. Di OddsFlow, model kami menggunakan data historis, performa tim, dan algoritma canggih untuk menghitung hasil yang paling mungkin untuk setiap pertandingan sepak bola.",
    faq2Q: "Seberapa akurat prediksi Anda?",
    faq2A: "Meskipun tidak ada prediksi yang dijamin, model AI kami dirancang untuk memberikan probabilitas dengan kepercayaan tinggi. Kami fokus pada akurasi jangka panjang dan optimisasi berkelanjutan. Selalu ingat: taruhan melibatkan risiko.",
    faq3Q: "Seberapa sering prediksi diperbarui?",
    faq3A: "Prediksi diperbarui setiap hari dengan data baru dan informasi pertandingan. Dalam kasus berita terbaru seperti cedera atau perubahan susunan pemain, model secara otomatis menyesuaikan probabilitas.",
    faq4Q: "Apakah Anda memberikan tips taruhan atau hanya statistik?",
    faq4A: "Kami fokus pada probabilitas objektif yang dihasilkan AI, bukan opini pribadi. Namun, kami mungkin sesekali menyoroti pilihan dengan kepercayaan tinggi berdasarkan model AI untuk pengguna yang mencari wawasan cepat.",
    faq5Q: "Apakah prediksi ini gratis untuk digunakan?",
    faq5A: "Ya. Prediksi taruhan AI harian kami sepenuhnya gratis, tanpa perlu mendaftar. Kami percaya semua orang harus memiliki akses ke alat taruhan cerdas berbasis data.",
    faq6Q: "Bisakah saya mengakses prediksi Anda di perangkat mobile?",
    faq6A: "Ya, OddsFlow sepenuhnya responsif untuk mobile, menawarkan akses tanpa hambatan di desktop, tablet, dan smartphone.",
    // Footer
    footerDesc: "Analisis odds sepak bola bertenaga AI untuk prediksi yang lebih cerdas.",
    product: "Produk",
    liveOdds: "Performa AI",
    popularLeagues: "Liga Populer",
    communityFooter: "Komunitas",
    globalChat: "Obrolan Global",
    userPredictions: "Prediksi Pengguna",
    todayMatches: "Pertandingan Hari Ini",
    company: "Perusahaan",
    aboutUs: "Tentang Kami",
    contact: "Kontak",
    blog: "Blog",
    legal: "Legal",
    termsOfService: "Ketentuan Layanan",
    privacyPolicy: "Kebijakan Privasi",
    responsibleGaming: "Perjudian Bertanggung Jawab",
    allRightsReserved: "Hak cipta dilindungi.",
    gamblingWarning: "Perjudian melibatkan risiko. Harap bertaruh dengan bijak.",
    disclaimer: "Penafian: OddsFlow menyediakan prediksi berbasis AI hanya untuk tujuan informasi dan hiburan. Kami tidak menjamin keakuratan prediksi dan tidak bertanggung jawab atas kerugian finansial apa pun. Perjudian melibatkan risiko. Harap bertaruh dengan bijak. Jika Anda atau seseorang yang Anda kenal memiliki masalah perjudian, silakan cari bantuan. Pengguna harus berusia 18+ tahun.",
  },
};

export default function SolutionPage() {
  const params = useParams();
  const urlLocale = (params.locale as string) || 'en';
  const locale = locales.includes(urlLocale as Locale) ? urlLocale : 'en';
  const selectedLang = localeToTranslationCode[locale as Locale] || 'EN';

  const localePath = (path: string): string => {
    if (locale === 'en') return path;
    return path === '/' ? `/${locale}` : `/${locale}${path}`;
  };

  // Helper function to get locale URL for language dropdown
  const getLocaleUrl = (targetLocale: Locale): string => {
    const currentPath = '/solution';
    return targetLocale === 'en' ? currentPath : `/${targetLocale}${currentPath}`;
  };

  const [langDropdownOpen, setLangDropdownOpen] = useState(false);
  const [user, setUser] = useState<User | null>(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  // Check auth session
  useEffect(() => {
    const checkUser = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      setUser(session?.user || null);
    };
    checkUser();

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event: any, session: any) => {
      setUser(session?.user || null);
    });

    return () => subscription.unsubscribe();
  }, []);

  // Translation function
  const t = (key: string): string => {
    return translations[selectedLang]?.[key] || translations['EN']?.[key] || key;
  };

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white flex flex-col relative">
      {/* Background */}
      <div className="fixed inset-0 z-0">
        <div className="absolute inset-0 bg-gradient-to-b from-[#0a0a0f] via-[#0d1117] to-[#0a0a0f]" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(16,185,129,0.1),transparent_50%)]" />
      </div>

      {/* Ambient Glow Effects */}
      <div className="fixed inset-0 z-[1] pointer-events-none overflow-hidden">
        <div className="absolute -top-20 -left-20 w-[600px] h-[600px] bg-emerald-500/8 rounded-full blur-[150px] animate-pulse" style={{ animationDuration: '4s' }} />
        <div className="absolute -top-20 -right-20 w-[500px] h-[500px] bg-cyan-500/8 rounded-full blur-[150px] animate-pulse" style={{ animationDuration: '5s', animationDelay: '1s' }} />
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-emerald-500/5 rounded-full blur-[200px]" />
      </div>

      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-black/20 backdrop-blur-xl border-b border-white/5">
        <div className="w-full px-4 sm:px-6 lg:px-12">
          <div className="flex items-center justify-between h-16">
            <Link href={localePath('/')} className="flex items-center gap-3 flex-shrink-0">
              <img src="/homepage/OddsFlow Logo2.png" alt="OddsFlow Logo" className="w-14 h-14 object-contain" />
              <span className="text-xl font-bold tracking-tight">OddsFlow</span>
            </Link>

            <div className="hidden md:flex items-center gap-6">
              <Link href={localePath('/')} className="text-gray-400 hover:text-white transition-colors text-sm font-medium">{t('home')}</Link>
              <Link href={localePath('/predictions')} className="text-gray-400 hover:text-white transition-colors text-sm font-medium">{t('predictions')}</Link>
              <Link href={localePath('/leagues')} className="text-gray-400 hover:text-white transition-colors text-sm font-medium">{t('leagues')}</Link>
              <Link href={localePath('/performance')} className="text-gray-400 hover:text-white transition-colors text-sm font-medium">{t('performance')}</Link>
              <Link href={localePath('/community')} className="text-gray-400 hover:text-white transition-colors text-sm font-medium">{t('community')}</Link>
              <Link href={localePath('/news')} className="text-gray-400 hover:text-white transition-colors text-sm font-medium">{t('news')}</Link>
              <Link href={localePath('/solution')} className="text-emerald-400 text-sm font-medium">{t('solution')}</Link>
              <Link href={localePath('/pricing')} className="text-gray-400 hover:text-white transition-colors text-sm font-medium">{t('pricing')}</Link>
            </div>

            <div className="flex items-center gap-2 sm:gap-3 flex-shrink-0">
              {/* Language Selector */}
              <div className="relative">
                <button
                  onClick={() => setLangDropdownOpen(!langDropdownOpen)}
                  className="flex items-center gap-2 px-3 py-2 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10 transition-all text-sm cursor-pointer"
                >
                  <FlagIcon code={locale} size={20} />
                  <span className="font-medium">{selectedLang}</span>
                  <svg
                    className={`w-4 h-4 transition-transform ${langDropdownOpen ? 'rotate-180' : ''}`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>

                {langDropdownOpen && (
                  <>
                    <div className="fixed inset-0 z-40" onClick={() => setLangDropdownOpen(false)} />
                    <div className="absolute right-0 mt-2 w-48 py-2 bg-gray-900 border border-white/10 rounded-xl shadow-xl z-50 max-h-80 overflow-y-auto">
                      {locales.map((loc) => (
                        <Link
                          key={loc}
                          href={getLocaleUrl(loc)}
                          className={`w-full flex items-center gap-3 px-4 py-2.5 hover:bg-white/10 transition-colors text-left cursor-pointer ${
                            locale === loc ? 'bg-emerald-500/20 text-emerald-400' : 'text-gray-300'
                          }`}
                        >
                          <FlagIcon code={loc} size={20} />
                          <span className="font-medium">{localeNames[loc]}</span>
                        </Link>
                      ))}
                    </div>
                  </>
                )}
              </div>

              {user ? (
                <Link href={localePath('/dashboard')} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10 transition-all cursor-pointer">
                  {user.user_metadata?.avatar_url || user.user_metadata?.picture ? (
                    <img src={user.user_metadata?.avatar_url || user.user_metadata?.picture} alt="" className="w-8 h-8 rounded-full object-cover" referrerPolicy="no-referrer" />
                  ) : (
                    <div className="w-8 h-8 rounded-full bg-gradient-to-r from-emerald-500 to-cyan-500 flex items-center justify-center text-black font-bold text-sm">
                      {user.user_metadata?.full_name?.charAt(0) || user.email?.charAt(0)?.toUpperCase() || 'U'}
                    </div>
                  )}
                  <span className="text-sm font-medium hidden sm:block">{user.user_metadata?.full_name || user.email?.split('@')[0]}</span>
                </Link>
              ) : (
                <>
                  <Link href={localePath('/login')} className="px-4 py-2 rounded-lg border border-white/20 text-white hover:bg-white/10 transition-all text-sm font-medium hidden sm:block cursor-pointer">{t('login')}</Link>
                  <Link href={localePath('/get-started')} className="px-5 py-2.5 rounded-lg bg-gradient-to-r from-emerald-500 to-cyan-500 text-black font-semibold text-sm hover:shadow-lg hover:shadow-emerald-500/25 transition-all cursor-pointer hidden sm:block">{t('getStarted')}</Link>
                </>
              )}

              {/* World Cup Special Button - Always Visible */}
              <Link
                href={localePath('/worldcup')}
                className="relative hidden sm:flex items-center gap-1.5 px-5 py-2.5 rounded-lg bg-gradient-to-r from-yellow-400 via-amber-500 to-yellow-400 shadow-[0_0_20px_rgba(251,191,36,0.5)] hover:shadow-[0_0_30px_rgba(251,191,36,0.7)] transition-all cursor-pointer group overflow-hidden hover:scale-105"
              >
                {/* Shimmer effect */}
                <span className="absolute inset-0 bg-gradient-to-r from-transparent via-white/60 to-transparent animate-shimmer" />
                <img
                  src="/homepage/FIFA-2026-World-Cup-Logo-removebg-preview.png"
                  alt="FIFA World Cup 2026"
                  className="h-5 w-auto object-contain relative z-10"
                />
                <span className="text-black font-semibold text-sm relative z-10">FIFA 2026</span>
              </Link>

              {/* Mobile Menu Button */}
              <button
                onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                className="md:hidden p-2 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10 transition-all"
                aria-label="Toggle menu"
              >
                {mobileMenuOpen ? (
                  <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                ) : (
                  <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* Mobile Menu Overlay */}
      {mobileMenuOpen && (
        <div className="fixed inset-0 z-[45] md:hidden">
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setMobileMenuOpen(false)} />
          <div className="absolute top-16 left-0 right-0 bg-gray-900/95 backdrop-blur-xl border-b border-white/10 shadow-2xl">
            <div className="px-4 py-4 space-y-1">
              {/* World Cup Special Entry */}
              <Link
                href={localePath('/worldcup')}
                onClick={() => setMobileMenuOpen(false)}
                className="relative flex items-center gap-3 px-4 py-3 rounded-xl transition-all bg-gradient-to-r from-yellow-400 via-amber-500 to-yellow-400 border-2 border-yellow-300 shadow-[0_0_15px_rgba(251,191,36,0.4)] overflow-hidden"
              >
                <span className="absolute inset-0 bg-gradient-to-r from-transparent via-white/50 to-transparent animate-shimmer" />
                <img
                  src="/homepage/FIFA-2026-World-Cup-Logo-removebg-preview.png"
                  alt="FIFA World Cup 2026"
                  className="h-8 w-auto object-contain relative z-10"
                />
                <span className="text-black font-extrabold relative z-10">FIFA 2026</span>
              </Link>

              {[
                { href: localePath('/'), label: t('home') },
                { href: localePath('/predictions'), label: t('predictions') },
                { href: localePath('/leagues'), label: t('leagues') },
                { href: localePath('/performance'), label: t('performance') },
                { href: localePath('/community'), label: t('community') },
                { href: localePath('/news'), label: t('news') },
                { href: localePath('/solution'), label: t('solution'), active: true },
                { href: localePath('/pricing'), label: t('pricing') },
              ].map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  onClick={() => setMobileMenuOpen(false)}
                  className={`block px-4 py-3 rounded-lg text-base font-medium transition-all ${
                    link.active
                      ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                      : 'text-gray-300 hover:bg-white/5 hover:text-white'
                  }`}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Spacer for fixed navbar */}
      <div className="h-16"></div>

      {/* Main Content */}
      <main className="relative z-10 flex-1">
        {/* Hero Section */}
        <section className="py-20 px-4">
          <div className="max-w-7xl mx-auto text-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              <span className="bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">
                {t('heroTitle')}
              </span>
            </h1>
            <p className="text-xl text-gray-400 max-w-3xl mx-auto">
              {t('heroSubtitle')}
            </p>
          </div>
        </section>

        {/* Signal API Section */}
        <section className="py-16 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div>
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/20 border border-blue-500/30 text-blue-400 text-sm font-medium mb-6">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  API
                </div>
                <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('signalApi')}</h2>
                <p className="text-gray-400 text-lg mb-8">{t('signalApiDesc')}</p>
                <ul className="space-y-3">
                  {[t('signalApiFeature1'), t('signalApiFeature2'), t('signalApiFeature3'), t('signalApiFeature4')].map((feature, i) => (
                    <li key={i} className="flex items-center gap-3 text-gray-300">
                      <svg className="w-5 h-5 text-emerald-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                      {feature}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 p-8">
                <div className="bg-[#0d1117] rounded-lg p-4 font-mono text-sm">
                  <div className="text-gray-500 mb-2">// Example API Response</div>
                  <div className="text-emerald-400">{'{'}</div>
                  <div className="ml-4 text-gray-300">"match_id": <span className="text-cyan-400">"12345"</span>,</div>
                  <div className="ml-4 text-gray-300">"prediction": <span className="text-cyan-400">"home_win"</span>,</div>
                  <div className="ml-4 text-gray-300">"confidence": <span className="text-yellow-400">0.87</span>,</div>
                  <div className="ml-4 text-gray-300">"odds_value": <span className="text-yellow-400">2.15</span></div>
                  <div className="text-emerald-400">{'}'}</div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* White Label Section */}
        <section className="py-16 px-4 bg-white/[0.02]">
          <div className="max-w-7xl mx-auto">
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div className="order-2 md:order-1">
                <div className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 p-8">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center">
                      <span className="text-white font-bold">Y</span>
                    </div>
                    <span className="text-xl font-bold">YourBrand</span>
                  </div>
                  <div className="space-y-4">
                    <div className="h-4 bg-white/10 rounded w-3/4"></div>
                    <div className="h-4 bg-white/10 rounded w-1/2"></div>
                    <div className="grid grid-cols-3 gap-4 mt-8">
                      <div className="h-20 bg-emerald-500/20 rounded-lg border border-emerald-500/30"></div>
                      <div className="h-20 bg-cyan-500/20 rounded-lg border border-cyan-500/30"></div>
                      <div className="h-20 bg-purple-500/20 rounded-lg border border-purple-500/30"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="order-1 md:order-2">
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-500/20 border border-purple-500/30 text-purple-400 text-sm font-medium mb-6">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" />
                  </svg>
                  White Label
                </div>
                <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('whiteLabel')}</h2>
                <p className="text-gray-400 text-lg mb-8">{t('whiteLabelDesc')}</p>
                <ul className="space-y-3">
                  {[t('whiteLabelFeature1'), t('whiteLabelFeature2'), t('whiteLabelFeature3'), t('whiteLabelFeature4')].map((feature, i) => (
                    <li key={i} className="flex items-center gap-3 text-gray-300">
                      <svg className="w-5 h-5 text-emerald-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                      {feature}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Native Ads Section */}
        <section className="py-16 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div>
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/20 border border-amber-500/30 text-amber-400 text-sm font-medium mb-6">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  Monetization
                </div>
                <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('nativeAds')}</h2>
                <p className="text-gray-400 text-lg mb-8">{t('nativeAdsDesc')}</p>
                <ul className="space-y-3">
                  {[t('nativeAdsFeature1'), t('nativeAdsFeature2'), t('nativeAdsFeature3'), t('nativeAdsFeature4')].map((feature, i) => (
                    <li key={i} className="flex items-center gap-3 text-gray-300">
                      <svg className="w-5 h-5 text-emerald-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                      {feature}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 p-8">
                <div className="space-y-4">
                  <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                    <div className="flex items-center gap-4">
                      <div className="w-16 h-16 bg-gradient-to-r from-amber-500/20 to-orange-500/20 rounded-lg flex items-center justify-center">
                        <span className="text-2xl">AD</span>
                      </div>
                      <div className="flex-1">
                        <div className="h-3 bg-white/20 rounded w-3/4 mb-2"></div>
                        <div className="h-2 bg-white/10 rounded w-1/2"></div>
                      </div>
                    </div>
                  </div>
                  <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                    <div className="flex items-center gap-4">
                      <div className="w-16 h-16 bg-gradient-to-r from-emerald-500/20 to-cyan-500/20 rounded-lg"></div>
                      <div className="flex-1">
                        <div className="h-3 bg-white/20 rounded w-2/3 mb-2"></div>
                        <div className="h-2 bg-white/10 rounded w-1/3"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Data Advantage Section */}
        <section className="py-16 px-4 bg-white/[0.02]">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/20 border border-emerald-500/30 text-emerald-400 text-sm font-medium mb-6">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
                Data Science
              </div>
              <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('dataAdvantage')}</h2>
              <p className="text-gray-400 text-lg max-w-3xl mx-auto">{t('dataAdvantageDesc')}</p>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 p-8">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-r from-blue-500 to-cyan-500 flex items-center justify-center mb-6">
                  <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
                  </svg>
                </div>
                <h3 className="text-2xl font-bold mb-4">{t('multiDimensional')}</h3>
                <p className="text-gray-400">{t('multiDimensionalDesc')}</p>
                <div className="mt-6 flex flex-wrap gap-2">
                  {['Team Form', 'Player Stats', 'H2H Records', 'Weather', 'Market Odds'].map((tag) => (
                    <span key={tag} className="px-3 py-1 rounded-full bg-white/5 border border-white/10 text-sm text-gray-400">{tag}</span>
                  ))}
                </div>
              </div>

              <div className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 p-8">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center mb-6">
                  <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                </div>
                <h3 className="text-2xl font-bold mb-4">{t('backtesting')}</h3>
                <p className="text-gray-400">{t('backtestingDesc')}</p>
                <div className="mt-6 grid grid-cols-3 gap-4 text-center">
                  <div>
                    <div className="text-2xl font-bold text-emerald-400">10+</div>
                    <div className="text-sm text-gray-500">Years Data</div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-cyan-400">50+</div>
                    <div className="text-sm text-gray-500">Leagues</div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-purple-400">200+</div>
                    <div className="text-sm text-gray-500">Variables</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Flexible Pricing Section */}
        <section className="py-16 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 p-8">
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-white/5 rounded-xl p-6 border border-white/10 text-center">
                    <div className="text-3xl font-bold text-emerald-400 mb-2">$0.01</div>
                    <div className="text-sm text-gray-400">Per Request</div>
                  </div>
                  <div className="bg-white/5 rounded-xl p-6 border border-white/10 text-center">
                    <div className="text-3xl font-bold text-cyan-400 mb-2">$99</div>
                    <div className="text-sm text-gray-400">Monthly</div>
                  </div>
                  <div className="col-span-2 bg-gradient-to-r from-emerald-500/20 to-cyan-500/20 rounded-xl p-6 border border-emerald-500/30 text-center">
                    <div className="text-3xl font-bold text-white mb-2">Custom</div>
                    <div className="text-sm text-gray-400">Enterprise Plans</div>
                  </div>
                </div>
              </div>
              <div>
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-green-500/20 border border-green-500/30 text-green-400 text-sm font-medium mb-6">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                  </svg>
                  Pricing
                </div>
                <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('flexiblePricing')}</h2>
                <p className="text-gray-400 text-lg mb-8">{t('flexiblePricingDesc')}</p>
                <ul className="space-y-3">
                  {[t('pricingFeature1'), t('pricingFeature2'), t('pricingFeature3'), t('pricingFeature4')].map((feature, i) => (
                    <li key={i} className="flex items-center gap-3 text-gray-300">
                      <svg className="w-5 h-5 text-emerald-400 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                      {feature}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Why Choose Us Section */}
        <section className="py-20 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <span className="text-emerald-400 text-sm font-semibold tracking-wider uppercase mb-4 block">{t('whyChooseUs')}</span>
              <h2 className="text-4xl md:text-5xl font-bold mb-4 italic">{t('whyChooseTitle')}</h2>
              <p className="text-gray-400 text-lg">{t('whyChooseSubtitle')}</p>
            </div>
            <div className="grid md:grid-cols-3 gap-6">
              {[
                { icon: (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                ), title: t('benefit1Title'), desc: t('benefit1Desc') },
                { icon: (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                ), title: t('benefit2Title'), desc: t('benefit2Desc') },
                { icon: (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                  </svg>
                ), title: t('benefit3Title'), desc: t('benefit3Desc') },
                { icon: (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                  </svg>
                ), title: t('benefit4Title'), desc: t('benefit4Desc') },
                { icon: (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192l-3.536 3.536M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-5 0a4 4 0 11-8 0 4 4 0 018 0z" />
                  </svg>
                ), title: t('benefit5Title'), desc: t('benefit5Desc') },
                { icon: (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 14l6-6m-5.5.5h.01m4.99 5h.01M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16l3.5-2 3.5 2 3.5-2 3.5 2z" />
                  </svg>
                ), title: t('benefit6Title'), desc: t('benefit6Desc') },
              ].map((benefit, i) => (
                <div
                  key={i}
                  className="group relative bg-gradient-to-br from-gray-900/80 to-gray-950/80 rounded-2xl border border-emerald-500/20 p-8 overflow-hidden cursor-pointer transition-all duration-300 hover:border-emerald-500/50 hover:shadow-[0_0_30px_rgba(16,185,129,0.15)]"
                >
                  {/* Shimmer effect on hover - white light */}
                  <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500">
                    <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000 ease-out" />
                  </div>

                  {/* Icon container */}
                  <div className="w-14 h-14 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 mb-6 relative z-10 group-hover:bg-emerald-500/30 transition-colors duration-300">
                    {benefit.icon}
                  </div>

                  {/* Content */}
                  <h3 className="text-xl font-bold mb-3 text-white relative z-10">{benefit.title}</h3>
                  <p className="text-gray-400 text-sm relative z-10">{benefit.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="py-16 px-4 bg-white/[0.02]">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('faqTitle')}</h2>
            </div>
            <div className="grid md:grid-cols-2 gap-6">
              {[
                { q: t('faq1Q'), a: t('faq1A') },
                { q: t('faq2Q'), a: t('faq2A') },
                { q: t('faq3Q'), a: t('faq3A') },
                { q: t('faq4Q'), a: t('faq4A') },
                { q: t('faq5Q'), a: t('faq5A') },
                { q: t('faq6Q'), a: t('faq6A') },
              ].map((faq, i) => (
                <div key={i} className="bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 p-6">
                  <h3 className="text-lg font-bold mb-3 text-white">{faq.q}</h3>
                  <p className="text-gray-400 text-sm leading-relaxed">{faq.a}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Contact CTA Section */}
        <section className="py-20 px-4">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('contactUs')}</h2>
            <p className="text-gray-400 text-lg mb-8">{t('contactUsDesc')}</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href={localePath('/contact')}
                className="px-8 py-4 rounded-xl bg-gradient-to-r from-emerald-500 to-cyan-500 text-black font-semibold text-lg hover:shadow-lg hover:shadow-emerald-500/25 transition-all"
              >
                {t('getInTouch')}
              </Link>
              <a
                href="mailto:enterprise@oddsflow.com"
                className="px-8 py-4 rounded-xl border border-white/20 text-white font-semibold text-lg hover:bg-white/10 transition-all flex items-center justify-center gap-2"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                enterprise@oddsflow.com
              </a>
            </div>
          </div>
        </section>
      </main>

<Footer localePath={localePath} t={t} locale={locale} />
    </div>
  );
}
